name: opslevel.yml schema validation

on:
  pull_request:
    paths:
      - '**/opslevel.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install ajv js-yaml

    - name: Find and validate all opslevel.yml files
      run: |
        # Find all opslevel.yml files in the repository
        files=$(find . -name "opslevel.yml")
          
        # Loop through each file and run the validation
        for file in $files; do
          echo "Validating $file"
          node tools/validate.js "$file"
        done
